# Check code health on every push
name: Code Quality Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Linter & Type Check
        run: npm run lint
      - name: Run Tests
        run: npm test
